spring:
  datasource:
    username: root
    password: Ric137!Marina!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

indexing-settings:
  user-agent: HeliontSearchBot/1.0 (+http://yourdomain.com/bot)
  referrer: http://www.google.com
  sites:
    - url: https://www.playback.ru/
      name: PlayBack.Ru
    - url: https://dombulgakova.ru/
      name: DomBulgakova.Ru










   








